name: Docker images

on:
  # push:
  #   branches: [main]
  schedule:
    - cron: "0 0 * * 2"
  release:
    types: [published]
  workflow_dispatch:

jobs:

    build:
      runs-on: ubuntu-latest

      steps:

      - uses: actions/checkout@v4

      - name: Get version tag
        id: get_tag
        run: |
          if [ ${{ startsWith(github.ref, 'refs/tags/') }} = true ]; then
            echo "tag=latest,${GITHUB_REF:10}" >>$GITHUB_OUTPUT
          else
            echo "tag=latest" >>$GITHUB_OUTPUT
          fi

      - name: Build and Publish bbox-server-qgis
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: sourcepole/bbox-server-qgis
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ steps.get_tag.outputs.tag }}"
          dockerfile: docker/Dockerfile-qgis-server

      - name: Build and Publish bbox-map-server-qgis
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          BUILD_DIR: bbox-map-server
        with:
          name: sourcepole/bbox-map-server-qgis
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          buildargs: BUILD_DIR
          tags: "${{ steps.get_tag.outputs.tag }}"
          dockerfile: docker/Dockerfile-qgis-server

      - name: Build and Publish bbox-tile-server
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          BUILD_DIR: bbox-tile-server
        with:
          name: sourcepole/bbox-tile-server
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          buildargs: BUILD_DIR
          tags: "${{ steps.get_tag.outputs.tag }}"
          dockerfile: docker/Dockerfile
